import GasCards from './components/gas/GasCards';
import NearestStation from './components/gas/NearestStation';
import StockCards from './components/stocks/StockCards';
import NewsSection from './components/news/NewsSection';
import MapView from './components/map/MapView';

export default function Home() {
      return (
            <main className="min-h-screen bg-[#f5f5f7]">

                  {/* Hero Tile - Light */}
                        <section className="bg-white px-6 py-20 text-center">
                                <p className="text-sm font-semibold tracking-[0.15em] text-[#0066cc] uppercase mb-4">
                                          FuelScope AI
                                                  </p>
                                                          <h1 className="text-[56px] font-semibold leading-[1.07] tracking-[-0.28px] text-[#1d1d1f] max-w-3xl mx-auto">
                                                                    Clean energy intelligence for smarter fuel insights.
                                                                            </h1>
                                                                                    <p className="mt-6 text-[17px] leading-[1.47] tracking-[-0.374px] text-[#1d1d1f] max-w-xl mx-auto">
                                                                                              Real-time gas prices, energy stocks, and AI-powered market news — all in one place.
                                                                                                      </p>
                                                                                                              <div className="mt-8 flex justify-center gap-4 flex-wrap">
                                                                                                                        <a href="#gas-prices" className="rounded-full bg-[#0066cc] px-6 py-3 text-[17px] text-white font-normal tracking-tight transition active:scale-95">
                                                                                                                                    Explore prices
                                                                                                                                              </a>
                                                                                                                                                        <a href="#news" className="rounded-full border border-[#0066cc] px-6 py-3 text-[17px] text-[#0066cc] font-normal tracking-tight transition active:scale-95">
                                                                                                                                                                    Read news
                                                                                                                                                                              </a>
                                                                                                                                                                                      </div>
                                                                                                                                                                                            </section>

                                                                                                                                                                                                  {/* Gas Prices Tile - Parchment */}
                                                                                                                                                                                                        <section id="gas-prices" className="bg-[#f5f5f7] px-6 py-20">
                                                                                                                                                                                                                <div className="max-w-5xl mx-auto">
                                                                                                                                                                                                                          <h2 className="text-[40px] font-semibold leading-[1.1] text-[#1d1d1f] mb-2">
                                                                                                                                                                                                                                      Regional Gas Prices
                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                          <p className="text-[17px] text-[#1d1d1f] mb-10 tracking-[-0.374px]">
                                                                                                                                                                                                                                                                      Real-time fuel prices across US East Coast regions
                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                          <GasCards />
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                              {/* Nearest Station Tile - White */}
                                                                                                                                                                                                                                                                                                                    <section className="bg-white px-6 py-20">
                                                                                                                                                                                                                                                                                                                            <div className="max-w-5xl mx-auto">
                                                                                                                                                                                                                                                                                                                                      <h2 className="text-[40px] font-semibold leading-[1.1] text-[#1d1d1f] mb-10">
                                                                                                                                                                                                                                                                                                                                                  Nearest Station
                                                                                                                                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                                                                                                                                      <NearestStation />
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                    </section>

                                                                                                                                                                                                                                                                                                                                                                                          {/* Stocks Tile - Dark */}
                                                                                                                                                                                                                                                                                                                                                                                                <section className="bg-[#272729] px-6 py-20">
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="max-w-5xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-[40px] font-semibold leading-[1.1] text-white mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                              Energy Stocks
                                                                                                                                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-[17px] text-[#cccccc] mb-10 tracking-[-0.374px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Live market data for top energy companies
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <StockCards />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* News Tile - Parchment */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <section id="news" className="bg-[#f5f5f7] px-6 py-20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="max-w-5xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-[40px] font-semibold leading-[1.1] text-[#1d1d1f] mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Energy News
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[17px] text-[#1d1d1f] mb-10 tracking-[-0.374px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          AI-summarized headlines from top energy sources
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <NewsSection />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Map Tile - White */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="bg-white px-6 py-20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="max-w-5xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-[40px] font-semibold leading-[1.1] text-[#1d1d1f] mb-10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Station Map
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <MapView />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <footer className="bg-[#f5f5f7] border-t border-[#e0e0e0] px-6 py-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="max-w-5xl mx-auto flex flex-col sm:flex-row justify-between items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-[12px] text-[#7a7a7a] tracking-[-0.12px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Copyright © 2026 FuelScope AI. All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-[12px] text-[#7a7a7a]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Built with Next.js 15 · Powered by GNews API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </footer>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
      );
}
